export enum StatusPedido {
  PEDIDO = 'PEDIDO',

  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',

  PAGO = 'PAGO',

  ENTREGUE = 'ENTREGUE',

  CANCELADO = 'CANCELADO',

  ESTORNADO = 'ESTORNADO',
}
